baseURL = "https://www.YOUR-WEBSITE-NAME.com"
languageCode = "en-us"
title = "ğŸŒ place site title here! (hugo.toml) ğŸ”§"

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related:"
  favicon = "favicon.png"
  # top nav, next and previous buttons
  topnav = true

  #list items
  datesinlist = false
  authorsinlist = false

  #footer items
  nextprev = true
  taglist = true
  showrss = true

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
